services:
  tradingview-app:
    build: ./frontend
    ports:
      - "3020:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
      - REACT_APP_BACKEND_URL=http://localhost:3021
    stdin_open: true
    tty: true
    restart: always
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3021:8081"
    volumes:
      - ./backend/data:/data
    environment:
      - PORT=8081
    restart: always
